root: true

env:
  browser: true
  node: true
  es2022: true

extends:
  - eslint:recommended
  - plugin:astro/recommended
  - prettier

parserOptions:
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions: [.astro]

rules:
  no-undef: off
  no-console: warn

overrides:
  - files: ["*.astro"]
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"

  - files: ["*.ts", "*.tsx"]
    extends: [plugin:@typescript-eslint/recommended]
    parser: "@typescript-eslint/parser"

  - files: ["*.tsx"]
    parserOptions:
      ecmaFeatures:
        jsx: true

  - files: ["*.astro", "*.ts", "*.tsx"]
    parserOptions:
      project: [./tsconfig.eslint.json]
    rules:
      "@typescript-eslint/consistent-type-exports": error
      "@typescript-eslint/consistent-type-imports": error
      "@typescript-eslint/no-useless-empty-export": error

  - files: ["*.md", "*.mdx"]
    parser: "eslint-plugin-markdownlint/parser"
    extends: ["plugin:markdownlint/recommended"]
    rules:
      markdownlint/md013:
        - error
        - line_length: 120
          heading_line_length: 120
          code_block_line_length: 120
