trailingComma: none
semi: false
singleQuote: true
printWidth: 120
endOfLine: auto

plugins: ['./node_modules/prettier-plugin-astro']
overrides:
  - files: '**/*.astro'
    options:
      parser: 'astro'
