// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    CodeBlock: typeof import('./src/components/content/code/code-block.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Header: typeof import('./src/components/header/header.vue')['default']
    HeaderItem: typeof import('./src/components/header/header-item.vue')['default']
    Heading2: typeof import('./src/components/content/headings/heading-2.vue')['default']
    Heading3: typeof import('./src/components/content/headings/heading-3.vue')['default']
    Heading4: typeof import('./src/components/content/headings/heading-4.vue')['default']
    HeadingLink: typeof import('./src/components/content/headings/heading-link.vue')['default']
    HeadSeo: typeof import('./src/components/head-seo.vue')['default']
    Image: typeof import('./src/components/content/image.vue')['default']
    InlineCode: typeof import('./src/components/content/code/inline-code.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.8.3_sass@1.54.0/node_modules/iles/dist/client/app/components/Island.vue')['default']
    Link: typeof import('./src/components/content/link.vue')['default']
    Logo: typeof import('./src/components/header/logo.vue')['default']
    MenuButton: typeof import('./src/components/header/menu-button.tsx')['default']
    Paragraph: typeof import('./src/components/content/paragraph.vue')['default']
    Picture: typeof import('./node_modules/.pnpm/@islands+images@0.8.1/node_modules/@islands/images/src/Picture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeButton: typeof import('./src/components/header/theme-button.tsx')['default']
  }
}
